### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by ZexinLi0w0** [muvanpersie/yolo-fastest-pytorch#3]
Thanks for sharing the code. Could you upload a pre-trained model for testing?

**Comment by muvanpersie** [comment]
sorry for replay so late. Here is the bdd100k pre-trained model link. [baiduyun](https://pan.baidu.com/s/1p7E7-8HuYrYcsurZ7sUqNA?pwd=yolo)

**Comment by ZexinLi0w0** [comment]
Thanks for your reply. Your model successfully solves the embedded deployment problem.
